# Generated by Django 3.2.10 on 2022-01-11 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220109_2003'),
        ('shops', '0004_alter_shop_shop_type'),
        ('orders', '0006_alter_orderitem_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='orders.OrderItem', to='products.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_shop', to='shops.shop'),
            preserve_default=False,
        ),
    ]
