# Generated by Django 4.0 on 2021-12-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
