# Generated by Django 3.2.10 on 2022-01-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_register',
            field=models.BooleanField(default=False),
        ),
    ]
